---
title: "Sense-checking Hendy's Model"
description: |
  A very brief sense-check of the COVID death modelling
author:
  - name: Mitchell Palmer
    url: https://mitchellpalmer.nz
date: 09-27-2021
categories:
  - New Zealand
  - COVID-19
  - Politics
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

There has been quite some [bruhaha](https://www.stuff.co.nz/national/politics/300414401/covid19-nz-rodney-jones-says-shaun-hendys-7000death-vaccine-model-doesnt-pass-plausibility-test) about a recent [estimate](https://cpb-ap-se2.wpmucdn.com/blogs.auckland.ac.nz/dist/d/75/files/2017/01/modelling-to-support-a-future-covid-19-strategy-for-aotearoa-new-zealand.pdf) from Shaun Hendy and his team at TPM that, were NZ to open up with 75% of the population fully vaccinated (or 80% of over-5s), approximately 7000 people could die. I am far from an expert on proper epidemiological modelling, so I will leave those critiques to others. What I want to do in this post is briefly sense-check Hendy's numbers against some numbers we do know -- vaccine efficacy and case-fatality rates, for instance -- and see whether the implications make sense.

Hendy's model predicts that roughly 7,000 people could die. Out of a population of roughly 5 million, that's a population-fatality rate (which I'll call $f_t$ for *fatality rate, total*) of 0.14% -- i.e., 14 in every 1000 New Zealanders would die of COVID in the next year. That number can be deconstructed as the average of the population-fatality rate of vaccinated people ($f_v$) and the population-fatality rate of unvaccinated people ($f_u$), weighted by the proportion of people vaccinated (which is a known quantity in this case -- 75%).

$$
f_t = 0.75f_v + 0.25f_u
$$

The efficacy of the Pfizer vaccine against death from the Delta variant appears to be [at least 90%](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1017309/S1362_PHE_duration_of_protection_of_COVID-19_vaccines_against_clinical_disease.pdf). For conservatism's sake, we'll say it is exactly 90%. This means that we can assume $f_v= (1-0.9)f_u$ -- i.e., the fatality rate among vaccinated people will be 90% less than that of unvaccinated people. Therefore, if you follow my algebra below, we find that the implied unvaccinated fatality rate is 0.43% -- i.e., 43 in every 1000 unvaccinated New Zealanders would die in the next 12 months.

$$
f_t = 0.75(1-0.9)f_u + 0.25f_u \\
f_u = \frac{1}{0.325}f_t \\
f_u = \frac{1}{0.325}\left(\frac{7000}{5\times10^6}\right) \\ 
f_u = 0.43\%
$$

This also implies a vaccinated fatality rate of 0.04%. Given a 75% vaccination rate, that means roughly 1600 vaccinated people (out of 3.75 million) and roughly 5400 unvaccinated people (out of 1.25 million) would die. 

Let us return to the fatality rate of the unvaccinated people. Your probability of dying from a disease is the product of two numbers: Your probability of catching that disease (what I'll call the 'infection rate' $i_u$) and your probability of dying from that disease, conditional on having caught it (which is the infection-fatality rate, which is well-known to most of us by now, but which I will call $d_u$).

$$
f_u = i_u \cdot d_u
$$

Unfortunately, we do not know what the true infection-fatality rate of COVID-19 is, because we simply do not know how many people have caught or died from COVID during the pandemic so far. Nonetheless, the *case fatality ratio* -- which measures the proportion of diagnosed COVID cases who have died -- is an acceptable proxy, so long as we redefine the infection rate to mean the likelihood of being *diagnosed*, rather than *infected*, with the disease.

Despite this accomodation, it is still difficult to find case-fatality rates for unvaccinated patients with delta in the rich world, given that the variant emerged just as most rich countries ramped up their vaccine programmes. Nonetheless, we can deal with an approximation that, where testing has kept up with the outbreak (if testing fails to keep up, the denominator of total cases becomes meaningless), most rich countries have had a case-fatality rate of roughly 2%. New Zealand's has been lower throughout the pandemic (roughly 1%), likely because our hospital capacity has not been stretched. Three factors lead me to believe the CFR would likely be lower than this baseline for unvaccinated people if this situation was to play out:

1. Happily, New Zealand's vaccination rates of the elderly have been strong (even today only roughly 20% of the over-65 population is not fully vaccinated, compared to roughly 60% of the overall population). Therefore, unvaccinated patients are likely to be younger than the average New Zealander and thus have much serious COVID.

2. We have learnt from previous outbreaks around the world. For instance, treatments like dexamethasone, validated by the RECOVERY trial in the UK, are now validated and avaliable, which can significantly reduce mortality.

3. A good percentage of the '25% unvaccinated' may well have recieved their first dose and thus will be at least partially protected from the virus.

Nonetheless, if we assume a 2% case-fatality rate, that implies that 21.5% of the unvaccinated population will catch COVID -- to such an extent that they would, in the status quo, get tested and be counted asa case -- within one year of the re-opening. Given the infectiousness of Delta, that is seems to my uneducated eye to be a plausible number. Obviously, as your assumptions about the CFR go down, the resulting implied infection rate goes up.

Hendy and his team *appear* to assume a case-fatality rate of 1.38%, based on [this study](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltext) which is based on data from Wuhan. I am sceptical of the extent to which this data is useful in the very different context of delta and the New Zealand health system, but nonetheless, the headline CFR lines up relatively well. Using this number, we find an implied infection rate of 31.1% of the unvaccinated.

Possibly the most important question is whether the health system could handle 21.5%/31.1% of the unvaccinated population getting COVID -- in addition to the smaller fraction, but likely larger total number (given the size of the vaccinated population), of breakthrough vaccinated cases -- over a 12 month period, while maintaining its standards in other areas. If we use the 21.5% figure, that is roughly 270,000 cases. For that question, we probably really need a deeper study (and perhaps to look at my rough [COVID-19 Vulnerability Index](https://mitchellpalmer.github.io/posts/2021-09-16-covid-19-vulnerability-index/)) of healthcare capacity and to consult the evidence on the speed at which (and what proportion of -- given not every COVID case needs to go to the hospital) those 270,000 cases will hit the system. If the healthcare system did in fact topple over, death rates could be significantly higher, even among vaccinated people. This may result, therefore, in the need to return to our policy from early in the pandemic of 'flattening the curve' to allow a relatively gentle transition to an endemic virus to which the population is essentially immune. 
