---
title: "The Closure of Yale-NUS and What It Means"
description: |
  Yale-NUS has been abolished. These are my thoughts.
author:
  - name: Mitchell Palmer
    url: https://mitchellpalmer.nz
    affiliation: Yale-NUS College
categories:
  - Singapore
date: 08-27-2021
output:
  distill::distill_article:
    self_contained: false
---

Last night, students, faculty and staff were summoned to a meeting called for this morning to hear of the unilateral decision made by the National University of Singapore (*the University* or *NUS*) to terminate its partnership with Yale University (*Yale*) and close Yale-NUS College (*YNC*, *Yale-NUS*, or *the College*). This was billed by NUS as a merger with the University's existing University Scholars Programme (*USP*) to form a *New College*, but it is far from it. In reality, Yale-NUS is being (gradually) abolished and having its purpose-built facilities taken over by a new institution that has little in common with the College.

This is obviously a very disappointing decision for the many of us who are committed to the vision of Yale-NUS. In particular, one feels for the inaugural faculty who built this institution from the ground-up and will now have it abolished before their eyes, without even a modicum of consultation. In this post, I want to offer my views on this decision and explain what it means for the future of the liberal arts in Asia.

As a foreigner in Singapore, I am not permitted to engage in political activity. Thus, I want to emphasise very strongly that this post is not a criticism of the Singapore government nor aimed at influencing Singaporean opinion. Rather, I seek to exercise my academic freedom, as guaranteed by the [Presidential Statement of Yale-NUS's first president](https://news.yale.edu/2012/07/19/presidential-statements-regarding-yale-nus-college) and the commitments made by NUS which are referred to therein,  to examine this particular decision of an independent *academic* institution and analyse its *academic* merit and implications. 

In particular, I wish to deal with four core issues: (1) Why this is a closure, not a merger; (2) Why the process followed during the closure was deeply flawed; (3) Why the closure lacks a coherent justification; and, (4) Why this closure will weaken the liberal arts in Asia, possibly irrevocably.

## Not a merger. A closure.

The literature distributed by NUS almost uniformly refers to this process as a 'merger' between YNC and USP. The press releases from Yale and the press coverage vacillated between calling it a merger and a closure. Make no mistake, it is a closure. Little of what makes Yale-NUS special will remain after the process is complete.

Yale-NUS College is a unique university-within-an-university. Though part of NUS for legal purposes, it has all of the trappings of an independent Liberal Arts College: It has small class sizes and students are only taught by professors. It has its own independent faculty, its own course structure, its own honours system, and even issues what are effectively its own degrees. Yale-NUS students can take NUS courses and use NUS facilities, with some limitations, but the opposite is not usually true. Administratively, it is also separate: Yale-NUS's President is answerable not to the NUS President and Board but to an independent governing board, half appointed by Yale and half appointed by the University, with a chair appointed by the Government. Crucially, it is also tied to an American institution, which subjects it to the scrutiny and standards (particularly around issues of academic freedom) of American academia. 

The New College will have none of that. Though some faculty would work at the New College, most of the courses students would take would be at NUS. That means, whereas Yale-NUS has its own economics, literature, chemistry, and physics (etc.) departments separate from those of the University, the New College will not. They will still attend the type of courses common at large research universities around the world, taught by TAs and with 500-person lectures. Thus two-thirds of their classes will be no different to those of NUS itself. It is essentially an additional programme for NUS students merged into a standard residential college, with somewhat selective entrance requirements. Yes, it will have a common curriculum and students will live on campus for some (but not all, unlike at Yale-NUS) of their degree tenure: But housing and a Common Curriculum do not a Liberal Arts College make. Put simply: Whereas YNC students typically answer the question "Where do you study?" with "Yale-NUS", one imagines that New College students, like the USP students before them, will answer with "NUS", not "New College".

Where two organisations 'merge' but only the core characteristics of one are maintained, while the other is used for its land and perhaps some of its employees, that is not a merger.

## Process? What process?

Faculty, staff, and students only received notice of the meeting at which the closure was announced roughly 17 hours before the meeting occurred. Before that notice (which had no details in it), only the most senior of the staff at the College had any inkling that something like this might be happening. Even very senior leaders and professors with long tenures at the college were kept in the dark. 

The meeting was called a "town hall", but it would be to insult the proud tradition of New England town halls to call it that. True town halls are an exercise in participatory democracy, where everyone can see and contribute to decisions being made. By contrast, during this morning's meeting, the decision of NUS — and just NUS (Yale noted that it "would have liked nothing better than to continue [YNC's] development") — to shut down our College was presented to the assembled (Zoom force-muted) mass of professors, students, and administrators as a *fait accompli*. 

Never once were Yale-NUS students or professors asked their views on this. Nor were they given the chance to offer constructive alternative ideas. 

This lack of preparation and consultation showed as the University was unable to answer relatively basic questions on how the transition from Yale-NUS to the New College would be managed. There was no consideration, for instance, of the almost impossible position which international students who are bonded to the Singapore government find themselves in, with their university soon about to show up on employers' Google searches as "defunct". Nor was there a coherent explanation of how a university with only 250 students (as it will be in 2025) could offer remotely the same diversity of courses as an institution of 1000 and why, given that impossibility, students would be expected to pay the same fees as today. Moreover, no matter how many times "a full Yale-NUS experience" was promised, the reality that Yale-NUS student organisations rely on sophomores, of which there will only be one more batch, to run them and will thus likely disappear was never grappled with. 

It also leaves one wondering about the state in which the New College will find itself once it is established. The initial establishment of Yale-NUS took roughly four years from the initial concept to enrolling students. New College, though a remarkably less ambitious project, will have only six months.

All told, this was a deeply callous way to approach the demolition of what, for some professors, has been a career's work and what, for many students, was a College on which they took a risk which had so far paid off and to which they had become deeply attached. When you talk to staff and students, the overriding emotion is shock, quickly followed in many cases by a sense of deep betrayal. 

The justification given for this ambush at the Q&A session after the Town Hall was that this is a 'strategic initiative of the University'. To be quite frank, that is laughable. Strategic initiatives are the very ones in which student and faculty buy-in are most important and in which errors are least acceptable. Determining the long-run strategy of a university should not be left in the hands of the executive team for the moment. It is simply too important for that. If you do not involve those who probably know best what is at stake, you are liable to make a tremendous error. Moreover, this attitude betrays a total lack of respect for the faculty and students which NUS — or Yale-NUS — itself selected and, in the case of students, has taught. If NUS cannot trust Yale-NUS students to contribute to discussions about the future of the University, how, in good conscience, can they send those same students into the workforce to contribute to even more important discussions?

The secrecy and subterfuge, apart from being deeply disrespectful, has also been tremendously practically disadvantageous to many. For instance, the new faculty which the College has hired and the Class of 2025 both would have made their final commitments to the College *after* NUS had already made up its mind to abolish it. Additionally, the faculty just completed an incredibly time-consuming and expensive review of the Common Curriculum, which will now be never be put into practice. By their insistence on ambush tactics — which seem designed to ensure that a campaign of press and political pressure could not save the College — the University has wasted all of our time and put many people in deeply unfair positions.

## The justification, or lack thereof.

Once people you speak to at Yale-NUS have proceeded through the stage of shock and betrayal, the next question is always: Why? 

Unfortunately, the answer remains unclear. The closest thing to a reason given was "we wish to expand access to the liberal arts in Singapore". That is a laudable goal, but it is unclear why it necessarily implies the abolition of Yale-NUS College. In fact, it seems to imply its expansion. There is spare space on UTown green which could be used for a new building; given the low acceptance rate, there are clearly thousands of willing students — even despite the incredibly unfavourable changes to financial aid which have been made recently — ready to attend; and, given the well-known glut of talent on the academic job market, there are presumably enough lecturers to fill any spots, despite recent shortages. Yale has also repeatedly stated its commitment to continuing its partnership with NUS, despite recent controversies about academic freedom. Whatever the problems with this model, they are issues that could have been surveyed in a transparent, open conversation with the faculty, Yale-NUS students, the wider NUS community, and the public.

Even the hackneyed business school trope of eliminating duplication cannot explain this decision. Yes, on the face of it, it seems unusual (but certainly not unprecedented: See the duplication of economics departments in business schools and arts and sciences schools around the world) for a university to have two parallel physics departments. But, for starters, NUS has committed to no redundancies for staff or faculty, making any reduction in duplication marginal at best. Secondly, a focus on reducing duplication is entirely at odds with the broader trends in Singapore: A university system intent on reducing duplication would not have recently set up multiple new autonomous universities: Instead, it would have consolidated them into one or two universities like NUS and NTU. 

If, as has been repeatedly stated today, the Yale-NUS experiment has succeeded, and it undeniably has, why is the University decided to abandon it just as it entered a new stage of maturity and continuity?

## What this means for the liberal arts in Asia

Outside of universities, it is often said that experience is the greatest teacher. Unfortunately, the experience of this great experiment is likely to teach the lesson that true liberal arts education cannot survive in Asia.

If the University which is consistently ranked the best in Asia cannot, in collaboration with an American university with hundreds of years of experience in liberal education, create a real liberal arts college that lasts more than a decade in full-scale operation, what hope, one might reasonably assume, does anyone else have? The next time an entrepreneurial university president suggests this idea — which has great merit, as suggested by the fact that even NUS wishes to "expand access to the liberal arts" — to his Minister of Education or to a donor, the benefactor will immediately ask "Has this been tried anywhere else?" The president will then have to admit that "Yes, it has" and even NUS and Yale couldn't make it work. Even if he attempts to explain our failure away, the idea will have been dealt a possibly mortal blow.

## Where to from here

It is unclear what, if anything, faculty, staff, and students can do about this decision. We may simply have to adapt. But, whatever happens, this has undeniably been handled terribly by the University. They have let down the students, faculty, and staff who took a risk and in many cases moved thousands of kilometres away from home to support and enjoy the vision of a liberal arts education in Asia.
